import os
import re
import json
import logging
import httpx
from typing import Dict, Any, Optional

logger = logging.getLogger("verity.llm_provider")

DETECTION_SYSTEM_PROMPT = """You are an AI text detection specialist. Analyze the given text and evaluate whether it was written by a human or generated by an AI language model.
Respond ONLY with a valid JSON object strictly formatted as:
{
  "ai_probability": <float between 0.0 and 1.0>,
  "human_probability": <float between 0.0 and 1.0>,
  "classification": "<Likely AI Generated | Likely Human Written | Uncertain / Mixed>",
  "confidence": "<High | Medium | Low>",
  "explanation": "<1-2 sentence concise evidence breakdown>"
}"""

def parse_llm_json_response(raw_text: str) -> Optional[Dict[str, Any]]:
    """Safely extracts and validates normalized JSON analysis from raw LLM output."""
    try:
        clean_text = raw_text.strip()
        if clean_text.startswith("```"):
            clean_text = re.sub(r"^```(?:json)?\s*", "", clean_text)
            clean_text = re.sub(r"\s*```$", "", clean_text)

        data = json.loads(clean_text)

        ai_prob = float(data.get("ai_probability", 0.5))
        ai_prob = round(max(0.02, min(0.98, ai_prob)), 2)
        human_prob = round(1.0 - ai_prob, 2)

        classification = data.get("classification")
        if not classification or classification not in ["Likely AI Generated", "Likely Human Written", "Uncertain / Mixed"]:
            if ai_prob >= 0.70:
                classification = "Likely AI Generated"
            elif ai_prob <= 0.35:
                classification = "Likely Human Written"
            else:
                classification = "Uncertain / Mixed"

        confidence = data.get("confidence", "Medium")
        if confidence not in ["High", "Medium", "Low"]:
            confidence = "Medium"

        explanation = data.get("explanation", "Analysis provided by external LLM provider.")

        return {
            "classification": classification,
            "ai_probability": ai_prob,
            "human_probability": human_prob,
            "confidence": confidence,
            "explanation": explanation
        }
    except Exception as e:
        logger.warning(f"Failed to parse LLM JSON response: {e}")
        return None


import time
import threading
from collections import defaultdict, deque

class LLMRateLimiter:
    """
    Thread-safe Rate Limiter and Cooldown Manager for LLM Providers.
    Protects against provider rate limit exhaustion (HTTP 429 / Quota Exceeded)
    by enforcing request rate windows, tracking rate-limit cooldowns, and
    providing round-robin provider rotation.
    """
    WINDOW_SECONDS = 10.0   # Sliding window size in seconds
    MAX_REQUESTS_PER_WINDOW = 5  # Max requests per provider in sliding window
    DEFAULT_COOLDOWN = 60.0  # Cooldown period in seconds when 429 occurs

    _lock = threading.Lock()
    _request_history: Dict[str, deque] = defaultdict(deque)
    _cooldown_until: Dict[str, float] = {}
    _last_provider_index: int = 0

    @classmethod
    def mark_rate_limited(cls, provider_name: str, cooldown_seconds: float = DEFAULT_COOLDOWN):
        """Puts a provider into a rate-limit cooldown period."""
        with cls._lock:
            cooldown_until = time.time() + cooldown_seconds
            cls._cooldown_until[provider_name] = cooldown_until
            logger.warning(
                f"[RateLimiter] Provider '{provider_name}' marked as RATE-LIMITED. "
                f"Cooldown active for {int(cooldown_seconds)}s (until {time.strftime('%H:%M:%S', time.localtime(cooldown_until))})."
            )

    @classmethod
    def is_rate_limited(cls, provider_name: str) -> bool:
        """Returns True if the provider is currently in a cooldown state."""
        with cls._lock:
            cooldown_until = cls._cooldown_until.get(provider_name, 0.0)
            if time.time() < cooldown_until:
                return True
            if provider_name in cls._cooldown_until:
                del cls._cooldown_until[provider_name]
                logger.info(f"[RateLimiter] Provider '{provider_name}' cooldown expired. Re-enabled for requests.")
            return False

    @classmethod
    def is_window_limit_reached(cls, provider_name: str) -> bool:
        """Checks if provider has reached max allowed requests within sliding time window."""
        with cls._lock:
            now = time.time()
            history = cls._request_history[provider_name]
            while history and history[0] <= now - cls.WINDOW_SECONDS:
                history.popleft()
            return len(history) >= cls.MAX_REQUESTS_PER_WINDOW

    @classmethod
    def is_ready(cls, provider_name: str) -> bool:
        """Checks if provider is active, not in cooldown, and under rate limit."""
        if cls.is_rate_limited(provider_name):
            return False
        if cls.is_window_limit_reached(provider_name):
            logger.warning(f"[RateLimiter] Provider '{provider_name}' sliding window limit ({cls.MAX_REQUESTS_PER_WINDOW} reqs/{int(cls.WINDOW_SECONDS)}s) reached.")
            return False
        return True

    @classmethod
    def record_request(cls, provider_name: str):
        """Records a successful request timestamp for rate window calculation."""
        with cls._lock:
            now = time.time()
            history = cls._request_history[provider_name]
            history.append(now)

    @classmethod
    def get_rotated_provider_order(cls, available_providers: List[str]) -> List[str]:
        """
        Returns provider list rotated using round-robin so consecutive requests
        do not depend solely on the same primary LLM provider.
        """
        with cls._lock:
            if not available_providers:
                return []
            cls._last_provider_index = (cls._last_provider_index + 1) % len(available_providers)
            start_idx = cls._last_provider_index
            return available_providers[start_idx:] + available_providers[:start_idx]

    @classmethod
    def get_status(cls) -> Dict[str, Any]:
        """Returns current status of rate limiter for telemetry & monitoring."""
        with cls._lock:
            now = time.time()
            cooldowns = {
                k: round(v - now, 1)
                for k, v in cls._cooldown_until.items()
                if v > now
            }
            active_counts = {
                k: len([t for t in v if t > now - cls.WINDOW_SECONDS])
                for k, v in cls._request_history.items()
            }
            return {
                "active_cooldowns": cooldowns,
                "recent_request_counts": active_counts,
                "max_rpm_setting": cls.MAX_REQUESTS_PER_WINDOW,
                "window_seconds": cls.WINDOW_SECONDS
            }


class BaseLLMProvider:
    name: str = "base"
    api_key_env: str = ""

    @classmethod
    def is_available(cls) -> bool:
        key = os.getenv(cls.api_key_env, "").strip()
        return bool(key)

    @classmethod
    def get_api_key(cls) -> str:
        return os.getenv(cls.api_key_env, "").strip()

    @classmethod
    def _sanitize_log_message(cls, message: str) -> str:
        """Ensures API keys are never exposed in logs."""
        key = cls.get_api_key()
        if key and len(key) > 4:
            message = message.replace(key, "[REDACTED_API_KEY]")
        return message

    @classmethod
    async def analyze_text(cls, text: str, timeout: float = 5.0, retries: int = 1) -> Optional[Dict[str, Any]]:
        """
        Executes AI detection analysis with rate limiting, timeouts, and safe retries.
        """
        if not cls.is_available():
            logger.info(f"Provider '{cls.name}' skipped: environment variable '{cls.api_key_env}' not set.")
            return None

        # Check rate limiter readiness & active cooldowns
        if not LLMRateLimiter.is_ready(cls.name):
            logger.warning(f"Provider '{cls.name}' skipped due to active rate-limiting / cooldown. Triggering immediate fallback.")
            return None

        sample_text = text[:2000]

        for attempt in range(retries + 1):
            try:
                result = await cls._execute_request(sample_text, timeout=timeout)
                if result:
                    LLMRateLimiter.record_request(cls.name)
                    logger.info(f"Provider '{cls.name}' successfully returned analysis (attempt {attempt + 1}).")
                    return result
            except httpx.HTTPStatusError as e:
                status_code = e.response.status_code if e.response else 0
                if status_code in (429, 403):
                    logger.warning(f"Provider '{cls.name}' returned HTTP {status_code} Rate Limit / Quota Exceeded. Activating 60s cooldown.")
                    LLMRateLimiter.mark_rate_limited(cls.name, cooldown_seconds=60.0)
                    return None  # Immediate fallback to next provider
                else:
                    err_msg = cls._sanitize_log_message(f"Provider '{cls.name}' HTTP {status_code} error: {str(e)}")
                    logger.warning(err_msg)
            except Exception as e:
                err_msg = cls._sanitize_log_message(f"Provider '{cls.name}' attempt {attempt + 1} error: {str(e)}")
                logger.warning(err_msg)

        return None

    @classmethod
    async def _execute_request(cls, text: str, timeout: float) -> Optional[Dict[str, Any]]:
        raise NotImplementedError


class GoogleProvider(BaseLLMProvider):
    name: str = "google"
    api_key_env: str = "GOOGLE_API_KEY"

    @classmethod
    async def _execute_request(cls, text: str, timeout: float) -> Optional[Dict[str, Any]]:
        api_key = cls.get_api_key()
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
        prompt = f"{DETECTION_SYSTEM_PROMPT}\n\nText to analyze:\n{text}"

        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(
                url,
                json={"contents": [{"parts": [{"text": prompt}]}]}
            )
            resp.raise_for_status()
            data = resp.json()
            raw_content = data["candidates"][0]["content"]["parts"][0]["text"]
            return parse_llm_json_response(raw_content)


class NVIDIAProvider(BaseLLMProvider):
    name: str = "nvidia"
    api_key_env: str = "NVIDIA_API_KEY"

    @classmethod
    async def _execute_request(cls, text: str, timeout: float) -> Optional[Dict[str, Any]]:
        api_key = cls.get_api_key()
        url = "https://integrate.api.nvidia.com/v1/chat/completions"

        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(
                url,
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": "meta/llama-3.1-70b-instruct",
                    "messages": [
                        {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
                        {"role": "user", "content": text}
                    ],
                    "temperature": 0.2
                }
            )
            resp.raise_for_status()
            data = resp.json()
            raw_content = data["choices"][0]["message"]["content"]
            return parse_llm_json_response(raw_content)


class GroqProvider(BaseLLMProvider):
    name: str = "groq"
    api_key_env: str = "GROQ_API_KEY"

    @classmethod
    async def _execute_request(cls, text: str, timeout: float) -> Optional[Dict[str, Any]]:
        api_key = cls.get_api_key()
        url = "https://api.groq.com/openai/v1/chat/completions"

        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(
                url,
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": "llama-3.3-70b-versatile",
                    "messages": [
                        {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
                        {"role": "user", "content": text}
                    ],
                    "temperature": 0.2
                }
            )
            resp.raise_for_status()
            data = resp.json()
            raw_content = data["choices"][0]["message"]["content"]
            return parse_llm_json_response(raw_content)


class OpenRouterProvider(BaseLLMProvider):
    name: str = "openrouter"
    api_key_env: str = "OPENROUTER_API_KEY"

    @classmethod
    async def _execute_request(cls, text: str, timeout: float) -> Optional[Dict[str, Any]]:
        api_key = cls.get_api_key()
        url = "https://openrouter.ai/api/v1/chat/completions"

        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(
                url,
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": "google/gemini-2.0-flash-001",
                    "messages": [
                        {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
                        {"role": "user", "content": text}
                    ],
                    "temperature": 0.2
                }
            )
            resp.raise_for_status()
            data = resp.json()
            raw_content = data["choices"][0]["message"]["content"]
            return parse_llm_json_response(raw_content)


PROVIDERS_MAP = {
    "google": GoogleProvider,
    "nvidia": NVIDIAProvider,
    "groq": GroqProvider,
    "openrouter": OpenRouterProvider
}
