import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();

  const outDir = path.resolve(__dirname, '../screenshots/ui-demo');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  const snap = async (name) => {
    const filePath = path.join(outDir, `${name}.png`);
    await page.screenshot({ path: filePath, fullPage: true });
    console.log(`Saved screenshot: ${filePath}`);
  };
  
  const snapViewport = async (name) => {
    const filePath = path.join(outDir, `${name}.png`);
    await page.screenshot({ path: filePath, fullPage: false });
    console.log(`Saved screenshot: ${filePath}`);
  };

  try {
    console.log('Navigating to landing page...');
    await page.goto('http://localhost:5173/');

    // 1. Hero initial state
    await page.waitForTimeout(1000);
    await snapViewport('1-hero-initial');

    // LiveDemo Animation cycle: 
    // It loops through typing -> analyzing -> ai_results -> paraphrasing -> recheck_analyzing -> human_results

    console.log('Waiting for Detect state (AI Detected!)...');
    await page.waitForSelector('text="3. AI Detected!"', { timeout: 15000 });
    await snapViewport('2-hero-detect');

    console.log('Waiting for Paraphrase state...');
    await page.waitForSelector('text="PARAPHRASING"', { timeout: 15000 });
    // Wait slightly so the text has time to type out
    await page.waitForTimeout(2000);
    await snapViewport('3-hero-paraphrase');

    console.log('Waiting for Re-verification state...');
    await page.waitForSelector('text="Re-verifying AI detection score..."', { timeout: 15000 });
    await snapViewport('4-hero-reverification');

    console.log('Waiting for Compare state...');
    await page.waitForSelector('text="6. Human-like!"', { timeout: 15000 });
    await snapViewport('5-hero-compare');

    // 6. Every remaining landing-page section
    console.log('Scrolling down landing page...');
    await page.evaluate(() => window.scrollBy(0, 800));
    await page.waitForTimeout(1000);
    await snapViewport('6-landing-features');

    await page.evaluate(() => window.scrollBy(0, 800));
    await page.waitForTimeout(1000);
    await snapViewport('6-landing-more-features');

    // 7. CTA section
    // 8. Complete footer
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    await page.waitForTimeout(1000);
    await snapViewport('7-landing-cta-footer');

    // 9. Login
    console.log('Navigating to Login...');
    await page.goto('http://localhost:5173/login');
    await page.waitForTimeout(1000);
    await snapViewport('9-login');

    // 10. Signup
    console.log('Navigating to Signup...');
    await page.goto('http://localhost:5173/signup');
    await page.waitForTimeout(1000);
    await snapViewport('10-signup');

    // To proceed with real dashboard data, we need to login
    // I will simulate logging in. Let's assume there is an input for email/password and a login button
    console.log('Logging in to dashboard...');
    await page.goto('http://localhost:5173/login');
    await page.waitForTimeout(1000);
    
    // Fill credentials (assuming test@example.com / password)
    // We will attempt to use standard selectors
    const emailInput = await page.$('input[type="email"]');
    const pwdInput = await page.$('input[type="password"]');
    if (emailInput && pwdInput) {
      await emailInput.fill('test@example.com');
      await pwdInput.fill('password123');
      await page.keyboard.press('Enter');
      await page.waitForTimeout(4000); // Wait for auth
    }

    // 11. Dashboard
    console.log('Navigating to Dashboard...');
    await page.goto('http://localhost:5173/dashboard');
    await page.waitForTimeout(2000);
    await snapViewport('11-dashboard');

    // 12. Documentation
    console.log('Navigating to Documentation...');
    await page.goto('http://localhost:5173/docs');
    await page.waitForTimeout(1000);
    await snapViewport('12-documentation');

    // 13. Analyze
    console.log('Navigating to Analyze...');
    await page.goto('http://localhost:5173/analyze');
    await page.waitForTimeout(2000);
    // Paste text and click analyze
    const textarea = await page.$('textarea');
    if (textarea) {
      await textarea.fill('This is an automated test sentence generated by AI to test the system capabilities and robustness.');
      const analyzeBtn = await page.$('button:has-text("Analyze")');
      if (analyzeBtn) await analyzeBtn.click();
      await page.waitForTimeout(4000); // Wait for results
    }
    await snapViewport('13-analyze');

    // 14. Paraphrase
    console.log('Navigating to Paraphrase...');
    await page.goto('http://localhost:5173/paraphrase');
    await page.waitForTimeout(2000);
    const paraphraseTextarea = await page.$('textarea');
    if (paraphraseTextarea) {
      await paraphraseTextarea.fill('This is an automated test sentence generated by AI to test the system capabilities and robustness.');
      const paraphraseBtn = await page.$('button:has-text("Paraphrase")');
      if (paraphraseBtn) await paraphraseBtn.click();
      await page.waitForTimeout(4000); // Wait for results
    }
    await snapViewport('14-paraphrase');

    // 15. Compare
    console.log('Navigating to Compare...');
    await page.goto('http://localhost:5173/compare');
    await page.waitForTimeout(2000);
    await snapViewport('15-compare');

    // 16. History
    console.log('Navigating to History...');
    await page.goto('http://localhost:5173/history');
    await page.waitForTimeout(2000);
    await snapViewport('16-history');

    // 17. Settings
    console.log('Navigating to Settings...');
    await page.goto('http://localhost:5173/settings');
    await page.waitForTimeout(2000);
    await snapViewport('17-settings');

  } catch (error) {
    console.error('Error during execution:', error);
  } finally {
    await browser.close();
    console.log('Done.');
  }
})();
